version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Mở port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount file cấu hình của bạn
      # - ./html:/usr/share/nginx/html  # Thư mục chứa file HTML (nếu cần)
    networks:
      - kong_network 
      
networks:
  kong_network:  # Đảm bảo tên mạng khớp với tên trong services
    driver: bridge
